### ISSUE TITLE
IMPORTANT: LICENSE file required

### ISSUE THREAD

**Issue by lazyparser** [sophgo/sophon-tools#1]
Hi all,

Thank you for sharing these amazing codes!

I've noticed that the LICENSE file is missing, and we may need it ASAP as the further collaborations will be based on it.

If you need any suggestions or helps on this topic, feel free to contact me.

**Comment by zetao-zhang-sophgo** [comment]
多谢您的提醒，这边计划采用LGPLv3开源协议，文件已经补充

**Comment by lazyparser** [comment]
感谢！

**Comment by lazyparser** [comment]
Fixed by bdd600b13930cb480b0f797989673b1393ace254
