### ISSUE TITLE
How to flash the image to eMMC/SPI NOR FLASH via usb device mode?

### ISSUE THREAD

**Issue by czg1997** [sophgo/sophon-tools#3]
Where can I find the the tool?

**Comment by zetao-zhang-sophgo** [comment]
* BM1684和BM1684X芯片不支持从USB设备启动，所以无法通过U盘/USB从设备模式烧录EMMC/SPI。
* BM1688和CV186AH芯片支持USB从模式设备烧录EMMC/SPI，参考文档链接：https://doc.sophgo.com/bm1688_sdk-docs/v1.7/docs_latest_release/docs/athena2-img/2_software_installation.html#id2
