### ISSUE TITLE
how to get 1688 power

### ISSUE THREAD

**Issue by OMG59E** [sophgo/sophon-tools#4]

**Comment by zetao-zhang-sophgo** [comment]
请问是获取BM1688芯片的功耗吗？

**Comment by OMG59E** [comment]
> 请问是获取BM1688芯片的功耗吗？

yes，想看看1688在不同负载下芯片和整机功耗情况

**Comment by zetao-zhang-sophgo** [comment]
* 整机功耗推荐使用外部的功率计获取。
* 芯片功耗需要按照BM1688的供电芯片方案自行获取。
  * 当前SE9设备的供电芯片并没有链接BM1688，无法在BM1688上获取芯片功耗情况
  * 推荐通过供电芯片的调试器链接PC读取芯片功耗信息
